import { Controller, Get, Post, Body, Patch, Param, Delete, Req, BadRequestException, NotFoundException } from '@nestjs/common';
import { CommandService } from './command.service';
import { CreateCommandDto } from './dto/create-command.dto';
import { UpdateCommandDto } from './dto/update-command.dto';
import { validateJwt } from "../services/verifyJwt"
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger';
import ResponseDto from "./dto/response-command.dto"

@ApiTags('Command generated by company')
@Controller('command')
export class CommandController {
  constructor(private readonly commandService: CommandService) { }

  @Post()
  @ApiOperation({ summary: "Give the company the ability to add new order" })
  @ApiResponse({
    status: 200,
    description: 'the response returns the details of the Order ',
    type: ResponseDto,
  })
  create(@Body() createCommandDto: CreateCommandDto, @Req() req) {
    try {
      let token = req.headers['authorization'];
      let infoUser = validateJwt(token);
      if (!infoUser) {
        throw new NotFoundException("حاول تسجل مرة أخرى")
      }
      //guard to add later, those who has company role are the one who can create the offer 
      const authentificatedId = infoUser.id;
      // console.log(infoUser);
      return this.commandService.create(createCommandDto, authentificatedId);
    } catch (e) {
      console.log(e)
      throw new BadRequestException('Try to login again')
    }

  }


  @Patch(':qrcode')
  @ApiResponse({
    status: 200,
    description: 'mabrouk',
  })
  scanedUserId(@Param('qrcode') qrcode: string, @Req() req) {
    let token = req.headers['authorization'];
    let infoUser = validateJwt(token);
    console.log(infoUser)

    if (!infoUser) {
      console.log("useeeeeeeeeeeeeeeeeer nit found")
      throw new NotFoundException("حاول تسجل مرة أخرى")
    }
    return this.commandService.scanedUserId(qrcode, infoUser.id);
  }





  @Get()
  findAll(@Req() req) {
    let token = req.headers['authorization'];
    let infoUser = validateJwt(token);
    console.log(infoUser)

    if (!infoUser) {
      console.log("useeeeeeeeeeeeeeeeeer nit found")
      throw new NotFoundException("حاول تسجل مرة أخرى")
    }
    return this.commandService.findAll(infoUser.id, infoUser.role );
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.commandService.findOne(+id);
  }

  @Patch(':id')
  update(@Param('id') id: string, @Body() updateCommandDto: UpdateCommandDto) {
    return this.commandService.update(+id, updateCommandDto);
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.commandService.remove(+id);
  }
}
